name: build
on:
  release:
    types: [published]

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Update changelog

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Upload changelog
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
        minecraft: ["1.19", "1.18"]
        loader: [fabric, forge]

    name: ${{matrix.loader}} ${{matrix.minecraft}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{matrix.loader}}-${{matrix.minecraft}}-${{github.ref_name}}

      - name: Setup Java ${{matrix.java}}
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java}}

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*-${{matrix.loader}}.jar

      - name: Upload release artifacts to Modrinth
        run: |
          ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
